### ISSUE TITLE
This error occurred after several operations

### ISSUE THREAD

**Issue by xyzhuzhou** [dylanaraps/fff#27] opened 2018-10-25 10:54 UTC
./fff: line 84: l2: bad array subscript

System:MacOs 10.13.6

**Comment by albinekb** [comment] 2018-10-25 12:57
Can you provide steps to reproduce?

**Comment by sukima** [comment] 2018-10-25 22:16
1.  Launch `./fff`
2.  Press <kbd>h</kbd>
3.  _note parent directory has sub directories and cursor is at top which is a directory_
4.  Press <kbd>l</kbd>
5.  Press <kbd>h</kbd>

[![asciicast](https://asciinema.org/a/px27lIN7zo8PjFQLnmBACFaDk.png)](https://asciinema.org/a/px27lIN7zo8PjFQLnmBACFaDk)

**Comment by sukima** [comment] 2019-01-04 19:38
@dylanaraps It is so still a problem:

[![asciicast](https://asciinema.org/a/nfKXEeBztnewNPralAiWoTXMN.svg)](https://asciinema.org/a/nfKXEeBztnewNPralAiWoTXMN)

1. `mkdir fff-example`
2. `cd ff-example`
3. `git clone git@github.com:dylanaraps/fff.git`
4. `cd fff`
5. `./fff`
6. Press <kbd>h</kbd>
7. Press <kbd>l</kbd>
8. Press <kbd>h</kbd>

Not really sure how to convince further.

**Comment by dylanaraps** [comment] 2019-01-04 20:32
It's not about convincing me, it's about helping me reproduce this issue. What version of bash are you using?

See: https://asciinema.org/a/4n8Or7e6GcWmaWon1eP3eghaA

**Comment by dylanaraps** [comment] 2019-01-04 20:41
This seems to be a macOS issue. Is everyone by any change using `bash3`?

**Comment by sukima** [comment] 2019-01-04 21:32
Oh!! yeah guess that makes sense:

```
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by dylanaraps** [comment] 2019-01-04 21:44
Should be fixed now :)

**Closed** 2019-01-04 21:44 UTC
